# Generated by Django 5.0.4 on 2024-04-12 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('email', models.TextField(primary_key=True, serialize=False, unique=True)),
                ('senha', models.IntegerField()),
            ],
        ),
    ]
